export const GET_ASSETS_BY_WORKSPACE_ID_REQUEST =
  "GET_ASSETS_BY_WORKSPACE_ID_REQUEST";
export const GET_ASSETS_BY_WORKSPACE_ID_SUCCESS =
  "GET_ASSETS_BY_WORKSPACE_ID_SUCCESS";
export const GET_ASSETS_BY_WORKSPACE_ID_FAILURE =
  "GET_ASSETS_BY_WORKSPACE_ID_FAILURE";

export const GET_WORKSPACES_REQUEST = "GET_WORKSPACES_REQUEST";
export const GET_WORKSPACES_SUCCESS = "GET_WORKSPACES_SUCCESS";
export const GET_WORKSPACES_FAILURE = "GET_WORKSPACES_FAILURE";

export const ADD_WORKSPACE_REQUEST = "ADD_WORKSPACE_REQUEST";
export const ADD_WORKSPACE_SUCCESS = "ADD_WORKSPACE_SUCCESS";
export const ADD_WORKSPACE_FAILURE = "ADD_WORKSPACE_FAILURE";

export const GET_EMPLOYEES_BY_WORKSPACE_ID_REQUEST =
  "GET_EMPLOYEES_BY_WORKSPACE_ID_REQUEST";
export const GET_EMPLOYEES_BY_WORKSPACE_ID_SUCCESS =
  "GET_EMPLOYEES_BY_WORKSPACE_ID_SUCCESS";
export const GET_EMPLOYEES_BY_WORKSPACE_ID_FAILURE =
  "GET_EMPLOYEES_BY_WORKSPACE_ID_FAILURE";

export const GET_LOCATIONS_BY_WORKSPACE_ID_REQUEST =
  "GET_LOCATIONS_BY_WORKSPACE_ID_REQUEST";
export const GET_LOCATIONS_BY_WORKSPACE_ID_SUCCESS =
  "GET_LOCATIONS_BY_WORKSPACE_ID_SUCCESS";
export const GET_LOCATIONS_BY_WORKSPACE_ID_FAILURE =
  "GET_LOCATIONS_BY_WORKSPACE_ID_FAILURE";

export const GET_VENDORS_BY_WORKSPACE_ID_REQUEST =
  "GET_VENDORS_BY_WORKSPACE_ID_REQUEST";
export const GET_VENDORS_BY_WORKSPACE_ID_SUCCESS =
  "GET_VENDORS_BY_WORKSPACE_ID_SUCCESS";
export const GET_VENDORS_BY_WORKSPACE_ID_FAILURE =
  "GET_VENDORS_BY_WORKSPACE_ID_FAILURE";

export const RESET_WORKSPACE = "RESET_WORKSPACE";

export const UPDATE_WORKSPACE_REQUEST = "UPDATE_WORKSPACE_REQUEST";
export const UPDATE_WORKSPACE_SUCCESS = "UPDATE_WORKSPACE_SUCCESS";
export const UPDATE_WORKSPACE_FAILURE = "UPDATE_WORKSPACE_FAILURE";
