export const GET_MYSELF_REQUEST = "GET_MYSELF_REQUEST";
export const GET_MYSELF_SUCCESS = "GET_MYSELF_SUCCESS";
export const GET_MYSELF_FAILURE = "GET_MYSELF_FAILURE";

export const UPDATE_MYSELF_REQUEST = "UPDATE_MYSELF_REQUEST";
export const UPDATE_MYSELF_SUCCESS = "UPDATE_MYSELF_SUCCESS";
export const UPDATE_MYSELF_FAILURE = "UPDATE_MYSELF_FAILURE";
