export const ADD_VENDOR_REQUEST = "ADD_VENDOR_REQUEST";
export const ADD_VENDOR_SUCCESS = "ADD_VENDOR_SUCCESS";
export const ADD_VENDOR_FAILURE = "ADD_VENDOR_FAILURE";

export const GET_VENDORS_BY_WORKSPACE_ID_REQUEST =
  "GET_VENDORS_BY_WORKSPACE_ID_REQUEST";
export const GET_VENDORS_BY_WORKSPACE_ID_SUCCESS =
  "GET_VENDORS_BY_WORKSPACE_ID_SUCCESS";
export const GET_VENDORS_BY_WORKSPACE_ID_FAILURE =
  "GET_VENDORS_BY_WORKSPACE_ID_FAILURE";

export const RESET_VENDORS = "RESET_VENDORS";
