export const ADD_EMPLOYEE_REQUEST = "ADD_EMPLOYEE_REQUEST";
export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_FAILURE = "ADD_EMPLOYEE_FAILURE";

export const GET_EMPLOYEES_BY_WORKSPACE_ID_REQUEST =
  "GET_EMPLOYEES_BY_WORKSPACE_ID_REQUEST";
export const GET_EMPLOYEES_BY_WORKSPACE_ID_SUCCESS =
  "GET_EMPLOYEES_BY_WORKSPACE_ID_SUCCESS";
export const GET_EMPLOYEES_BY_WORKSPACE_ID_FAILURE =
  "GET_EMPLOYEES_BY_WORKSPACE_ID_FAILURE";

export const RESET_EMPLOYEES = "RESET_EMPLOYEES";
