export const ADD_LOCATION_REQUEST = "ADD_LOCATION_REQUEST";
export const ADD_LOCATION_SUCCESS = "ADD_LOCATION_SUCCESS";
export const ADD_LOCATION_FAILURE = "ADD_LOCATION_FAILURE";

export const GET_LOCATIONS_BY_WORKSPACE_ID_REQUEST =
  "GET_LOCATIONS_BY_WORKSPACE_ID_REQUEST";
export const GET_LOCATIONS_BY_WORKSPACE_ID_SUCCESS =
  "GET_LOCATIONS_BY_WORKSPACE_ID_SUCCESS";
export const GET_LOCATIONS_BY_WORKSPACE_ID_FAILURE =
  "GET_LOCATIONS_BY_WORKSPACE_ID_FAILURE";

export const RESET_LOCATIONS = "RESET_LOCATIONS";
